name: "Bump Version"

on:
#  pull_request:
#    branches:
#      - master
#      - develop
  push:
    branches:
      - master
#      - develop

# What this action does;
# - Creates a release notes .md
# - Updates the version in package json using semantic-release
# - Pushes a new commit to github using the new tag
# - The new tagged commit triggers a travis release build
# - Does not create the github release (see travis.yml for that)

jobs:
  bump-version:
    name: Bump version (${{ github.sha }})
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 16
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/npm
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}